### ISSUE TITLE
Edit, spin 포커스 rect 표시

### ISSUE THREAD

**Issue by hancom-wsjung** [hancom-io/hnc-office-addin-ctrl#16]

**Comment by hancom-wsjung** [comment]
## 참고사항 - css 정의 순서에 따른 적용 우선 순위

**스타일 명시도**
1. 인라인스타일 - 우선순위가 가장 높음
2. id 스타일
3. 클래스 스타일
4. 태그스타일

**소스코드상에서의 순서**
```css
.hnc-editor:hover {
    border-color: var(--hnc-control-border-color-hover);
}
.hnc-editor:disabled {
    border-color: var(--hnc-control-border-color-disabled);
}
```
순서를 바꾸면 disabled 되었어도 hover 면 테두리색이 hover 색으로 나타난다.
```css
.hnc-editor:disabled {
    border-color: var(--hnc-control-border-color-disabled);
}
/* disabled 되었어도 hover 면 테두리색이 hover로 나타남 */
.hnc-editor:hover {
    border-color: var(--hnc-control-border-color-hover);
}
```
