### ISSUE TITLE
멀티브라우저 test

### ISSUE THREAD

**Issue by hancom-wsjung** [hancom-io/hnc-office-addin-ctrl#18]
Slider : 하기 코드 chrome 종속적임. firefox등 다른 브라우저에서 테스트필요.

```javascript
let foreColor = window.getComputedStyle(slider,null).color;
let backColor = window.getComputedStyle(slider,null).borderColor;
```
Slider는 webkit 계열만 구현됨. thumb 관련해서 moz(firefox), IE, edge 에서 구현 필요
```css
.hnc-slider::-webkit-slider-thumb {
    -webkit-appearance: none; /* Chrome, Safari, Edge, Opera 에서 원래 형태 감춤 */
```
combobox : 하기 코드 test 안됨

```css
.hnc-combobox::-ms-expand {
    display: none; /* IE10, IE11 에서 원래 형태 숨김 - 테스트 안됨 */
}
```
spin : 하기 코드 테스트 안됨
```css
.hnc-spin { 
    -moz-apperance: textfield; /* Firefox 내부 화살표 감춤. 테스트 안됨. */
```
