### ISSUE TITLE
groupbox caption이 ""경우 separator 여백이 보정되어야 함

### ISSUE THREAD

**Issue by hancom-wsjung** [hancom-io/hnc-office-addin-ctrl#20]
하기 margin-left로 여백을 주기때문에 caption=="" 이어도 여백이 생김
```css
.hnc-groupbox > .hnc-groupbox-caption::after {
    content:"";
    margin-left: 10px; /* 왼쪽 캡션과의 여백 */
    flex: 1; /* 증가 너비 */
    height: 1px;
    background-color: var(--hnc-control-background-accent2);
}
```
