### ISSUE TITLE
slider Focus Rect 보정 필요.

### ISSUE THREAD

**Issue by hancom-wsjung** [hancom-io/hnc-office-addin-ctrl#29]
하단 여백이 좁음

![image](https://user-images.githubusercontent.com/70936450/99137185-4de35680-266c-11eb-8853-a3871e6dc33b.png)

**Comment by hancom-wsjung** [comment]
## 참고사항 - css border-box를 활용한 정확한 좌표 계산

**slider의 구현**
하기와 같이 margin 1px 높이 2px로 슬라이더 트랙바를 그리고, .hnc-slider::before 를 absolute로 배치하여 focus rect를 표시함. 이때 thumb가 10px 이므로 focus rect의 높이는 12px 로 함.
```css
.hnc-slider {
    /* box-sizing: content-box; 디폴트라 생략 */
    /* margin: 1px; 상위 요소로부터 상속받음 */
    padding: 0;
    height: 2px;
}
.hnc-slider::before {
    content: "";
    display: inline-block;
    position: absolute;
    box-sizing: border-box;  /* padding, border를 포함한 크기 */
    left: 0;
    top: 0px; 
    width: 100%;
    height: 12px;
```
**결과화면**

![image](https://user-images.githubusercontent.com/70936450/99214828-8887f300-2814-11eb-8119-58d95cfbe027.png)

**slider focus rect 의 top 위치 보정**
```css
top: -4px; /* (12[height] - 2[focus border 1 * 2(상, 하)] - 2[track]) / 2 = 4px */
```
